// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../Components/Icon.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import * as PageHeader from "../Components/PageHeader.mjs";

function PageCareersProjectManager(Props) {
  return React.createElement(MainPage.make, {
              title: "Software Project Manager at Divertise Asia",
              keywords: "Artificial Intelligence, Design, Fullstack, API, Server",
              description: "Be a professional Software Project Manager at Divertise Asia",
              children: null
            }, React.createElement(PageHeader.make, {
                  className: "bg-gradient-color1 pt-5",
                  title: "Careers",
                  subtitle: "Project Manager"
                }), React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-row"
                        }, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), React.createElement("h3", {
                              className: "align-self-center"
                            }, "What are the requirements?")), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "Bachelors / University degree in related field"), React.createElement("li", undefined, "Having 1-3 years of relevant work experiences"), React.createElement("li", undefined, "Have a good working knowledge of project estimation techniques"), React.createElement("li", undefined, "Coordination and planning of project activities to ensure smooth execution"), React.createElement("li", undefined, "Must possess excellent communication skills in Thai and English"), React.createElement("li", undefined, "Strong communication skill, ability to perform formal communication and reporting, and lead meetings with creditability"), React.createElement("li", undefined, "Strong analytical skills and interpersonal skills, good in people management skill and team supervisory"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-row"
                        }, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), React.createElement("h3", {
                              className: "align-self-center"
                            }, "What will I be doing?")), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "Ensure that project-lifecycle deliverables consistently completed to agreed budget and schedule constraints"), React.createElement("li", undefined, "Develop and manage a detailed project schedule and work plan"), React.createElement("li", undefined, "Work closely with your team to understand motivation drivers, morale and job contribution/satisfaction levels in order to enhance your team engagement"), React.createElement("li", undefined, "Coordination and planning of project activities to ensure smooth execution"), React.createElement("li", undefined, "Partner with leaders to evaluate tools, processes and workflows and introduce techniques and best practices to improve efficiency"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-row"
                        }, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), React.createElement("h3", {
                              className: "align-self-center"
                            }, "When can I start?")), React.createElement("div", {
                          className: "ul-li-padding-none p-4 pl-5"
                        }, React.createElement("p", undefined, "It is recommended to apply 1-2 months prior to start date.")))), React.createElement("div", {
                  className: "footer-intern bg-gradient-color2"
                }, React.createElement("div", {
                      className: "container pt-5 pb-4"
                    }, React.createElement("div", {
                          className: "row d-block text-center text-white"
                        }, React.createElement("h2", {
                              className: "text-white -text-uppercase"
                            }, "Ready To Apply?"), React.createElement("div", {
                              className: "d-flex justify-content-center flex-wrap"
                            }, React.createElement("p", undefined, "Send us your resume and porfolio to "), React.createElement("p", undefined, React.createElement("a", {
                                      className: "pr-1 pl-1 -font-weight-bold text-color1 -text-underline-none",
                                      href: "mailto:careers@divertise.asia",
                                      target: "_blank"
                                    }, "careers@divertise.asia")), React.createElement("p", undefined, "and we'll get back to you soon!"))))));
}

var make = PageCareersProjectManager;

export {
  make ,
  
}
/* Icon Not a pure module */
