// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../Components/Icon.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Popup from "../Components/Popup.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import * as PageHeader from "../Components/PageHeader.mjs";
import * as ContactForm from "../Components/ContactForm.mjs";

function PageInternshipDesign(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setPopupBuildOpen = match[1];
  var isPopupBuildOpen = match[0];
  return React.createElement(MainPage.make, {
              title: "Designer Internship at Divertise Asia",
              keywords: "Artificial Intelligence, Design, Fullstack, API, Server",
              description: "Have your internship with Divertise Asia",
              children: null
            }, React.createElement(PageHeader.make, {
                  className: "bg-gradient-color1 pt-5",
                  title: "Internship",
                  subtitle: "Art & Design"
                }), React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "buildyourideas-btn btn btn-line-color1 d-inline-block d-sm-none",
                          onClick: (function (param) {
                              return Curry._1(setPopupBuildOpen, (function (param) {
                                            return !isPopupBuildOpen;
                                          }));
                            })
                        }, "Build Your Ideas"), React.createElement(Popup.make, {
                          isOpen: isPopupBuildOpen,
                          className: "buildyouridea-popup",
                          closeOnBgClick: false,
                          closeFunc: (function (param) {
                              return Curry._1(setPopupBuildOpen, (function (param) {
                                            return false;
                                          }));
                            }),
                          children: null
                        }, React.createElement("div", undefined, React.createElement("h3", undefined, "Build Your Ideas"), React.createElement("p", undefined, "Tell us about what you need. We will get back to you within 1 working day")), React.createElement(ContactForm.make, {})), React.createElement("h3", undefined, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), "What are the requirements?"), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "Strong communication skills"), React.createElement("li", undefined, "Minimum 2.50 GPA"), React.createElement("li", undefined, "Design-related major / Art and design background"), React.createElement("li", undefined, "Experience with computer graphic software (ex. Adobe Photoshop, Adobe illustrator etc.)"), React.createElement("li", undefined, "Some experience with 3D or 2D art"), React.createElement("li", undefined, "Skills in digital illustration is preferred, but not required"), React.createElement("li", undefined, "Portfolio is required"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("h3", undefined, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), "What will I be doing?"), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "Working on application/AI projects for UI/UX"), React.createElement("li", undefined, "Working in Adobe XD, Photoshop, and Illustrator."), React.createElement("li", undefined, "Implementing designs in HTML/CSS"), React.createElement("li", undefined, "Work at our office at BTS Chidlom station Monday-Friday 10:00-18:00"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("h3", undefined, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), "When can I start?"), React.createElement("div", {
                          className: "ul-li-padding-none p-4 pl-5"
                        }, React.createElement("p", undefined, "It is recommended to apply 1-2 months prior to start date."), React.createElement("p", undefined, "You are required to intern for minimum of 2 months")))), React.createElement("div", {
                  className: "footer-intern bg-gradient-color2"
                }, React.createElement("div", {
                      className: "container pt-5 pb-4"
                    }, React.createElement("div", {
                          className: "row d-block text-center text-white"
                        }, React.createElement("h2", {
                              className: "text-white -text-uppercase"
                            }, "Ready To Apply?"), React.createElement("div", {
                              className: "d-flex justify-content-center flex-wrap"
                            }, React.createElement("p", undefined, "Send us your resume and porfolio to "), React.createElement("p", undefined, React.createElement("a", {
                                      className: "pr-1 pl-1 -font-weight-bold text-color1 -text-underline-none",
                                      href: "mailto:careers@divertise.asia"
                                    }, "careers@divertise.asia")), React.createElement("p", undefined, "and we'll get back to you soon!")), React.createElement("p", {
                              className: "-text-small-title text-color1"
                            }, "*Please include your preferred start and end date of the internship in the email")))));
}

var make = PageInternshipDesign;

export {
  make ,
  
}
/* Icon Not a pure module */
