// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../Components/Icon.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import * as PageHeader from "../Components/PageHeader.mjs";

function PageCareersSales(Props) {
  return React.createElement(MainPage.make, {
              title: "Designer at Divertise Asia",
              keywords: "Artificial Intelligence, Design, Fullstack, API, Server",
              description: "Be a professional Designer (3 months contract) at Divertise Asia",
              children: null
            }, React.createElement(PageHeader.make, {
                  className: "bg-gradient-color1 pt-5",
                  title: "Careers",
                  subtitle: "Sales Executive (Software) ",
                  time: "(3 months contract)"
                }), React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-row"
                        }, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), React.createElement("h3", {
                              className: "align-self-center"
                            }, "What are the requirements?")), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "1-2 years experiences in Sales IT Software"), React.createElement("li", undefined, "Bachelor's degree in any fields"), React.createElement("li", undefined, "Fluent in Thai and English communication is a plus"), React.createElement("li", undefined, "B2B Sales experiences"), React.createElement("li", undefined, "Strong Business Development is the must"), React.createElement("li", undefined, "Willing to try new challenge"), React.createElement("li", undefined, "Proactive personality and good communication skill"), React.createElement("li", undefined, "Plus, if you have knowledge in HTML/CSS/JavaScript"), React.createElement("li", undefined, "Plus, if you experience in Business Development or Sales management role in a software development services company or technology consulting"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-row"
                        }, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), React.createElement("h3", {
                              className: "align-self-center"
                            }, "What will I be doing?")), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "Identify and analyze market for potential customers and find new customers to generate income for the company"), React.createElement("li", undefined, "Negotiating the terms of an agreement and closing sales"), React.createElement("li", undefined, "Gain a clear understanding of customer's businesses and requirements"), React.createElement("li", undefined, "Strong networking in sales or able to contact with potential customers to promote the services of the company"), React.createElement("li", undefined, "Perform business research and ideate the right approach to use for a multitude of business opportunities. "), React.createElement("li", undefined, "Understand and speak to trends in startups and technology"), React.createElement("li", undefined, "Develop and implement sales strategies and plans to drive customer needs to achieve sales goals"), React.createElement("li", undefined, "Conduct business and foster relationships with prospects and customers"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-row"
                        }, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), React.createElement("h3", {
                              className: "align-self-center"
                            }, "When can I start?")), React.createElement("div", {
                          className: "ul-li-padding-none p-4 pl-5"
                        }, React.createElement("p", undefined, "It is recommended to apply 1-2 months prior to start date.")))), React.createElement("div", {
                  className: "footer-intern bg-gradient-color2"
                }, React.createElement("div", {
                      className: "container pt-5 pb-4"
                    }, React.createElement("div", {
                          className: "row d-block text-center text-white"
                        }, React.createElement("h2", {
                              className: "text-white -text-uppercase"
                            }, "Ready To Apply?"), React.createElement("div", {
                              className: "d-flex justify-content-center flex-wrap"
                            }, React.createElement("p", undefined, "Send us your resume and porfolio to "), React.createElement("p", undefined, React.createElement("a", {
                                      className: "pr-1 pl-1 -font-weight-bold text-color1 -text-underline-none",
                                      href: "mailto:careers@divertise.asia",
                                      target: "_blank"
                                    }, "careers@divertise.asia")), React.createElement("p", undefined, "and we'll get back to you soon!"))))));
}

var make = PageCareersSales;

export {
  make ,
  
}
/* Icon Not a pure module */
