// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../Components/Icon.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Popup from "../Components/Popup.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import * as PageHeader from "../Components/PageHeader.mjs";
import * as ContactForm from "../Components/ContactForm.mjs";

function PageCareersDesigner(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setPopupBuildOpen = match[1];
  var isPopupBuildOpen = match[0];
  return React.createElement(MainPage.make, {
              title: "Designer at Divertise Asia",
              keywords: "Artificial Intelligence, Design, Fullstack, API, Server",
              description: "Be a professional Designer at Divertise Asia",
              children: null
            }, React.createElement(PageHeader.make, {
                  className: "bg-gradient-color1 pt-5",
                  title: "Careers",
                  subtitle: "Designer"
                }), React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "buildyourideas-btn btn btn-line-color1 d-inline-block d-sm-none",
                          onClick: (function (param) {
                              return Curry._1(setPopupBuildOpen, (function (param) {
                                            return !isPopupBuildOpen;
                                          }));
                            })
                        }, "Build Your Ideas"), React.createElement(Popup.make, {
                          isOpen: isPopupBuildOpen,
                          className: "buildyouridea-popup",
                          closeOnBgClick: false,
                          closeFunc: (function (param) {
                              return Curry._1(setPopupBuildOpen, (function (param) {
                                            return false;
                                          }));
                            }),
                          children: null
                        }, React.createElement("div", undefined, React.createElement("h3", undefined, "Build Your Ideas"), React.createElement("p", undefined, "Tell us about what you need. We will get back to you within 1 working day")), React.createElement(ContactForm.make, {})), React.createElement("h3", undefined, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), "What are the requirements?"), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "1-3 years experienced with visual designs (Preferably web/UI designs)"), React.createElement("li", undefined, "Proficient with Photoshop and Illustrator"), React.createElement("li", undefined, "Keeping up with latest design trends"), React.createElement("li", undefined, "Enjoy learning and willing to take on challenging tasks"), React.createElement("li", undefined, "Good problem-solving skills"), React.createElement("li", undefined, "Presentation skill"), React.createElement("li", undefined, "Intermediate level of English or higher"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("h3", undefined, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), "What will I be doing?"), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "UX/UI design for website and applications"), React.createElement("li", undefined, "Wireframe development and create prototypes (Using Adobe XD, InVision etc.)"), React.createElement("li", undefined, "Work closely with developers"), React.createElement("li", undefined, "Graphic design"), React.createElement("li", undefined, "Helping implement designs in HTML/CSS"), React.createElement("li", undefined, "Attend client meeting in both Thai and English"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("h3", undefined, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), "When can I start?"), React.createElement("div", {
                          className: "ul-li-padding-none p-4 pl-5"
                        }, React.createElement("p", undefined, "It is recommended to apply 1-2 months prior to start date.")))), React.createElement("div", {
                  className: "footer-intern bg-gradient-color2"
                }, React.createElement("div", {
                      className: "container pt-5 pb-4"
                    }, React.createElement("div", {
                          className: "row d-block text-center text-white"
                        }, React.createElement("h2", {
                              className: "text-white -text-uppercase"
                            }, "Ready To Apply?"), React.createElement("div", {
                              className: "d-flex justify-content-center flex-wrap"
                            }, React.createElement("p", undefined, "Send us your resume and porfolio to "), React.createElement("p", undefined, React.createElement("a", {
                                      className: "pr-1 pl-1 -font-weight-bold text-color1 -text-underline-none",
                                      href: "mailto:careers@divertise.asia",
                                      target: "_blank"
                                    }, "careers@divertise.asia")), React.createElement("p", undefined, "and we'll get back to you soon!"))))));
}

var make = PageCareersDesigner;

export {
  make ,
  
}
/* Icon Not a pure module */
