// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import * as PageHeader from "../Components/PageHeader.mjs";

function PageCareersDeveloperAssignment(Props) {
  return React.createElement(MainPage.make, {
              title: "Developer at Divertise Asia",
              keywords: "Artificial Intelligence, Design, Fullstack, API, Server",
              description: "Be a full-stack developer at Divertise Asia",
              children: null
            }, React.createElement(PageHeader.make, {
                  className: "bg-gradient-color1 pt-5",
                  title: "Careers",
                  subtitle: "Developer"
                }), React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-wrap",
                          id: "assignment"
                        }, React.createElement("div", {
                              className: "col-12 col-md-6"
                            }, React.createElement("h3", undefined, "Your Assignment"), React.createElement("ul", {
                                  className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                                }, React.createElement("li", undefined, "Ask any questions within first 7 days of assignment "), React.createElement("li", undefined, "Submit your GIT repository url within 14 days of assignment"), React.createElement("li", undefined, "Feel free to add any feature you want"), React.createElement("li", undefined, "Be ready to answer any question about your code and to edit it")), React.createElement("h3", undefined, "Requirements"), React.createElement("ul", {
                                  className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                                }, React.createElement("li", undefined, "Host the project on a public git repository"), React.createElement("li", undefined, "Make the webpage and its components using Rescript"), React.createElement("li", undefined, "Show a header that contains \"Name: YourName\""), React.createElement("li", undefined, "Show 9 random colored squares"))), React.createElement("div", {
                              className: "col-12 col-md-6"
                            }, React.createElement("h3", undefined, "Possible Output"), React.createElement("ol", {
                                  className: "ul-li-padding-none ul-li-dash p-4 pl-3 -lineheight-large"
                                }, React.createElement("img", {
                                      className: "md-3",
                                      src: "/static/images/possible_output.png",
                                      width: "100%"
                                    }))))), React.createElement("div", {
                      className: "text-center"
                    }, React.createElement("a", {
                          className: "btn",
                          href: "mailto:careers@divertise.asia"
                        }, "Submit"))), React.createElement("div", {
                  className: "footer-intern bg-gradient-color2"
                }, React.createElement("div", {
                      className: "container pt-5 pb-4"
                    }, React.createElement("div", {
                          className: "row d-block text-center text-white"
                        }, React.createElement("h2", {
                              className: "text-white -text-uppercase"
                            }, "Ready To Apply?"), React.createElement("div", {
                              className: "d-flex justify-content-center flex-wrap"
                            }, React.createElement("p", undefined, "Send us your resume and porfolio to "), React.createElement("p", undefined, React.createElement("a", {
                                      className: "pr-1 pl-1 -font-weight-bold text-color1 -text-underline-none",
                                      href: "mailto:careers@divertise.asia",
                                      target: "_blank"
                                    }, "careers@divertise.asia")), React.createElement("p", undefined, "and we'll get back to you soon!"))))));
}

var make = PageCareersDeveloperAssignment;

export {
  make ,
  
}
/* react Not a pure module */
