// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Logo from "../Components/Logo.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";

function Page404(Props) {
  return React.createElement(MainPage.make, {
              title: "404",
              keywords: "",
              description: "Not found on Divertise Asia",
              children: null
            }, React.createElement(Logo.make, {}), React.createElement("h2", {
                  className: "-text-space"
                }, "404"));
}

var make = Page404;

export {
  make ,
  
}
/* Logo Not a pure module */
