// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../Components/Icon.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Popup from "../Components/Popup.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import * as PageHeader from "../Components/PageHeader.mjs";
import * as ContactForm from "../Components/ContactForm.mjs";

function PageCareersDeveloper(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setPopupBuildOpen = match[1];
  var isPopupBuildOpen = match[0];
  return React.createElement(MainPage.make, {
              title: "Developer at Divertise Asia",
              keywords: "Artificial Intelligence, Design, Fullstack, API, Server",
              description: "Be a full-stack developer at Divertise Asia",
              children: null
            }, React.createElement(PageHeader.make, {
                  className: "bg-gradient-color1 pt-5",
                  title: "Careers",
                  subtitle: "Developer"
                }), React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "buildyourideas-btn btn btn-line-color1 d-inline-block d-sm-none",
                          onClick: (function (param) {
                              return Curry._1(setPopupBuildOpen, (function (param) {
                                            return !isPopupBuildOpen;
                                          }));
                            })
                        }, "Build Your Ideas"), React.createElement(Popup.make, {
                          isOpen: isPopupBuildOpen,
                          className: "buildyouridea-popup",
                          closeOnBgClick: false,
                          closeFunc: (function (param) {
                              return Curry._1(setPopupBuildOpen, (function (param) {
                                            return false;
                                          }));
                            }),
                          children: null
                        }, React.createElement("div", undefined, React.createElement("h3", undefined, "Build Your Ideas"), React.createElement("p", undefined, "Tell us about what you need. We will get back to you within 1 working day")), React.createElement(ContactForm.make, {})), React.createElement("h3", undefined, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), "What are the requirements?"), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "Intermediate English (verbal)"), React.createElement("li", undefined, "Basic programming knowledge (Python/ReasonML is preferred)"), React.createElement("li", undefined, "Proficiency in one of modern programming languages"), React.createElement("li", undefined, "IDE familiarity"), React.createElement("li", undefined, "Basic problem solving skills"), React.createElement("li", undefined, "Git/SVN knowledge is a plus but not required"), React.createElement("li", undefined, "Can take criticism and responsive to feedback"), React.createElement("li", undefined, "Interest in latest trends"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("h3", undefined, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), "What will I be doing?"), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "Working in application/AI projects"), React.createElement("li", undefined, "Working in fullstack development from deployment on AWS, frontend in Reason, and backend in Python/Django"), React.createElement("li", undefined, "Work at our office at BTS Chidlom station Monday-Friday 10:00-18:00"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("h3", undefined, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), "When can I start?"), React.createElement("div", {
                          className: "ul-li-padding-none p-4 pl-5"
                        }, React.createElement("p", undefined, "It is recommended to apply 1-2 months prior to start date.")))), React.createElement("div", {
                  className: "footer-intern bg-gradient-color2"
                }, React.createElement("div", {
                      className: "container pt-5 pb-4"
                    }, React.createElement("div", {
                          className: "row d-block text-center text-white"
                        }, React.createElement("h2", {
                              className: "text-white -text-uppercase"
                            }, "Ready To Apply?"), React.createElement("div", {
                              className: "d-flex justify-content-center flex-wrap"
                            }, React.createElement("p", undefined, "Send us your resume and porfolio to "), React.createElement("p", undefined, React.createElement("a", {
                                      className: "pr-1 pl-1 -font-weight-bold text-color1 -text-underline-none",
                                      href: "mailto:careers@divertise.asia",
                                      target: "_blank"
                                    }, "careers@divertise.asia")), React.createElement("p", undefined, "and we'll get back to you soon!"))))));
}

var make = PageCareersDeveloper;

export {
  make ,
  
}
/* Icon Not a pure module */
