// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Links from "../Links.mjs";
import * as Popup from "../Components/Popup.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import Link from "next/link";
import * as PageHeader from "../Components/PageHeader.mjs";
import * as ContactForm from "../Components/ContactForm.mjs";

function PageContact(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setPopupBuildOpen = match[1];
  var isPopupBuildOpen = match[0];
  return React.createElement(MainPage.make, {
              title: "Contact Us",
              keywords: "divertise asia, thailand",
              description: "Get in contact with Divertise Asia",
              children: null
            }, React.createElement(PageHeader.make, {
                  className: "bg-gradient-color1 pt-5 page-contacts",
                  title: "Contact Us"
                }), React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row py-5 d-block"
                    }, React.createElement("div", {
                          className: "buildyourideas-btn btn btn-line-color1 d-inline-block d-sm-none",
                          onClick: (function (param) {
                              return Curry._1(setPopupBuildOpen, (function (param) {
                                            return !isPopupBuildOpen;
                                          }));
                            })
                        }, "Build Your Ideas"), React.createElement(Popup.make, {
                          isOpen: isPopupBuildOpen,
                          className: "buildyouridea-popup",
                          closeOnBgClick: false,
                          closeFunc: (function (param) {
                              return Curry._1(setPopupBuildOpen, (function (param) {
                                            return false;
                                          }));
                            }),
                          children: null
                        }, React.createElement("div", undefined, React.createElement("h3", undefined, "Build Your Ideas"), React.createElement("p", undefined, "Tell us about what you need. We will get back to you within 1 working day")), React.createElement(ContactForm.make, {})), React.createElement("h3", undefined, "Looking for technological experts to help you with your product?"), React.createElement("input", {
                          className: "contact-page_invisible-input",
                          id: "emailInput"
                        }), React.createElement("p", undefined, "Please contact us via ", React.createElement("a", {
                              className: "contact-link text-color-2",
                              href: "mailto:contact@divertise.asia",
                              target: "_blank"
                            }, "this email")), React.createElement("h3", {
                          className: "pt-5"
                        }, "Looking to join our team?"), React.createElement("p", undefined, "Please read our job descriptions ", React.createElement(Link, {
                              href: Links.careers,
                              children: React.createElement("a", {
                                    className: "contact-link"
                                  }, "here")
                            }), ", and send your resume to ", React.createElement("a", {
                              className: "contact-link text-color-2",
                              href: "mailto:careers@divertise.asia",
                              target: "_blank"
                            }, "this email")))), React.createElement("div", {
                  className: "footer-title bg-gradient-color2"
                }, React.createElement("p", undefined, "If you are interested in joining our team, just send your portfolio to", React.createElement("a", {
                          className: "text-contact",
                          href: "mailto:careers@divertise.asia",
                          target: "_blank"
                        }, "careers@divertise.asia"))));
}

var make = PageContact;

export {
  make ,
  
}
/* Popup Not a pure module */
