// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../Components/Icon.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import * as PageHeader from "../Components/PageHeader.mjs";

function PageInternshipDev(Props) {
  return React.createElement(MainPage.make, {
              title: "Developer Internship at Divertise Asia",
              keywords: "Artificial Intelligence, Design, Fullstack, API, Server",
              description: "Have your internship with Divertise Asia",
              children: null
            }, React.createElement(PageHeader.make, {
                  className: "bg-gradient-color1 pt-5",
                  title: "Internship",
                  subtitle: "Developer"
                }), React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-row"
                        }, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), React.createElement("h3", {
                              className: "align-self-center"
                            }, "What are the requirements?")), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "Strong communication skills"), React.createElement("li", undefined, "Minimum 2.50 GPA"), React.createElement("li", undefined, "Programming-related major / Logic background"), React.createElement("li", undefined, "Some experience with Python, OCaml, or other language"), React.createElement("li", undefined, "Skills in GIT would be helpful, but not required"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-row"
                        }, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), React.createElement("h3", {
                              className: "align-self-center"
                            }, "What will I be doing?")), React.createElement("ul", {
                          className: "ul-li-padding-none ul-li-dash p-4 pl-5 -lineheight-large"
                        }, React.createElement("li", undefined, "Working in application/ai projects"), React.createElement("li", undefined, "Full Stack Development"), React.createElement("li", undefined, "Functional Programming"), React.createElement("li", undefined, "AWS"), React.createElement("li", undefined, "Learn new skills and implement them into your projects."), React.createElement("li", undefined, "Hybrid work at BTS Chidlom station once/two times a week 10:00-18:00"))), React.createElement("div", {
                      className: "row pt-5 d-block"
                    }, React.createElement("div", {
                          className: "d-flex flex-row"
                        }, React.createElement(Icon.make, {
                              iconType: /* Pen */8,
                              className: "mr-4"
                            }), React.createElement("h3", {
                              className: "align-self-center"
                            }, "When can I start?")), React.createElement("div", {
                          className: "ul-li-padding-none p-4 pl-5"
                        }, React.createElement("p", undefined, "It is recommended to apply 1-2 months prior to start date."), React.createElement("p", undefined, "You are required to intern for minimum of 2 months")))), React.createElement("div", {
                  className: "footer-intern bg-gradient-color2"
                }, React.createElement("div", {
                      className: "container pt-5 pb-4"
                    }, React.createElement("div", {
                          className: "row d-block text-center text-white"
                        }, React.createElement("h2", {
                              className: "text-white -text-uppercase"
                            }, "Ready To Apply?"), React.createElement("div", {
                              className: "d-flex justify-content-center flex-wrap"
                            }, React.createElement("p", undefined, "Send us your resume and porfolio to "), React.createElement("p", undefined, React.createElement("a", {
                                      className: "pr-1 pl-1 -font-weight-bold text-color1 -text-underline-none",
                                      href: "mailto:careers@divertise.asia",
                                      target: "_blank"
                                    }, "careers@divertise.asia")), React.createElement("p", undefined, "and we'll get back to you soon!")), React.createElement("p", {
                              className: "-text-small-title text-color1"
                            }, "*Please include your prefered start and end date of the internship in the email")))));
}

var make = PageInternshipDev;

export {
  make ,
  
}
/* Icon Not a pure module */
