// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Logo from "../Components/Logo.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Popup from "../Components/Popup.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import * as ContactForm from "../Components/ContactForm.mjs";

function Page404(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setPopupBuildOpen = match[1];
  var isPopupBuildOpen = match[0];
  return React.createElement(MainPage.make, {
              title: "404",
              keywords: "",
              description: "Not found on Divertise Asia",
              children: null
            }, React.createElement("div", {
                  className: "buildyourideas-btn btn btn-line-color1 d-inline-block d-sm-none",
                  onClick: (function (param) {
                      return Curry._1(setPopupBuildOpen, (function (param) {
                                    return !isPopupBuildOpen;
                                  }));
                    })
                }, "Build Your Ideas"), React.createElement(Popup.make, {
                  isOpen: isPopupBuildOpen,
                  className: "buildyouridea-popup",
                  closeOnBgClick: false,
                  closeFunc: (function (param) {
                      return Curry._1(setPopupBuildOpen, (function (param) {
                                    return false;
                                  }));
                    }),
                  children: null
                }, React.createElement("div", undefined, React.createElement("h3", undefined, "Build Your Ideas"), React.createElement("p", undefined, "Tell us about what you need. We will get back to you within 1 working day")), React.createElement(ContactForm.make, {})), React.createElement(Logo.make, {}), React.createElement("h2", {
                  className: "-text-space"
                }, "404"));
}

var make = Page404;

export {
  make ,
  
}
/* Logo Not a pure module */
