// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../Components/Icon.mjs";
import * as Links from "../Links.mjs";
import * as React from "react";
import * as MainPage from "../Components/MainPage.mjs";
import * as PageHeader from "../Components/PageHeader.mjs";
import * as ImageBackground from "../Components/ImageBackground.mjs";
import * as InternshipProgram from "../Components/InternshipProgram.mjs";

function PageCareers(Props) {
  return React.createElement(MainPage.make, {
              title: "Careers at Divertise Asia",
              keywords: "Artificial Intelligence, Design, Fullstack, API, Server",
              description: "Join our team",
              children: null
            }, React.createElement(PageHeader.make, {
                  className: "bg-gradient-color1 pt-5",
                  title: "Careers"
                }), React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row py-5 d-block text-center -text-uppercase"
                    }, React.createElement("h3", undefined, "Positions at Divertise Asia"), React.createElement("div", {
                          className: "row pt-5"
                        }, React.createElement(InternshipProgram.make, {
                              title: "Developer",
                              imageURL: "/static/images/position-dev.jpg",
                              href: Links.careersdeveloper,
                              iconType: /* Code */2
                            }), React.createElement(InternshipProgram.make, {
                              title: "Design Engineer",
                              imageURL: "/static/images/position-design.jpg",
                              href: Links.careersdesigner,
                              iconType: /* Pen */8
                            }), React.createElement(InternshipProgram.make, {
                              title: "Software Project Manager",
                              imageURL: "/static/images/position-dev.jpg",
                              href: Links.careersprojectmanager,
                              iconType: /* Code */2
                            }), React.createElement(InternshipProgram.make, {
                              title: "Sales Executive (Software)",
                              imageURL: "/static/images/position-design.jpg",
                              href: Links.careerssales,
                              iconType: /* Pen */8
                            }))), React.createElement("div", {
                      className: "row d-block text-center"
                    }, React.createElement("h3", {
                          className: "-text-uppercase"
                        }, "Internship Program"), React.createElement("p", {
                          className: "col-md-10 col-sm-12 program-text-title"
                        }, "You will get a chance to get your hands on application development and work closely with our friendly team."), React.createElement("div", {
                          className: "row -text-uppercase"
                        }, React.createElement(InternshipProgram.make, {
                              className: "image-background",
                              title: "App & Ai Dev",
                              imageURL: "/static/images/position-game.jpg",
                              href: Links.internshipdeveloper,
                              iconType: /* Code */2
                            }), React.createElement(InternshipProgram.make, {
                              title: "Art & Design",
                              imageURL: "/static/images/position-art.jpg",
                              href: Links.internshipdesign,
                              iconType: /* Pen */8
                            })))), React.createElement("div", {
                  className: "-bg-grey mt-5"
                }, React.createElement("div", {
                      className: "container pt-5 text-center"
                    }, React.createElement("h3", {
                          className: "-text-uppercase"
                        }, "Who are we looking for ?"), React.createElement("div", {
                          className: "row py-5 career_lookingfor"
                        }, React.createElement("div", {
                              className: "col-md-4 col-xs-12 pb-3"
                            }, React.createElement(ImageBackground.make, {
                                  className: " ",
                                  src: "/static/images/flexible.png"
                                }), React.createElement("h4", undefined, "Flexible"), React.createElement("p", undefined, "Our core work hours make it easy for your schdule to fit your lifestyle. We're flexible so you can be too.")), React.createElement("div", {
                              className: "col-md-4 col-xs-12  pb-3"
                            }, React.createElement(ImageBackground.make, {
                                  className: " ",
                                  src: "/static/images/lovelearning.png"
                                }), React.createElement("h4", undefined, "Open Minded"), React.createElement("p", undefined, "There's always more than one way to do something. We're always open to ideas.")), React.createElement("div", {
                              className: "col-md-4 col-xs-12  pb-3"
                            }, React.createElement(ImageBackground.make, {
                                  className: " ",
                                  src: "/static/images/openminded.png"
                                }), React.createElement("h4", undefined, "Love Learning"), React.createElement("p", undefined, "Do you like learning? We do! Here at Divertise we like to keep up with the latest tech."))))), React.createElement("div", {
                  className: "-bg-color1 "
                }, React.createElement("div", {
                      className: "container pt-5 text-center looking-for"
                    }, React.createElement("h3", {
                          className: "-text-uppercase"
                        }, "Team Benefits"), React.createElement("div", {
                          className: "row py-5 justify-content-center"
                        }, React.createElement("div", {
                              className: "col-6 col-md pb-3 team-benefits"
                            }, React.createElement(Icon.make, {
                                  iconType: /* Laptop */9
                                }), React.createElement("h6", {
                                  className: "icon-title"
                                }, "Hybrid Work")), React.createElement("div", {
                              className: "col-6 col-md pb-3 team-benefits"
                            }, React.createElement(Icon.make, {
                                  iconType: /* Clock */1
                                }), React.createElement("h6", {
                                  className: "icon-title"
                                }, "Flexible Working Time")), React.createElement("div", {
                              className: "col-6 col-md pb-3 team-benefits"
                            }, React.createElement(Icon.make, {
                                  iconType: /* Drink */3
                                }), React.createElement("h6", {
                                  className: "icon-title"
                                }, "Snacks & Drinks")), React.createElement("div", {
                              className: "col-6 col-md pb-3 team-benefits"
                            }, React.createElement(Icon.make, {
                                  iconType: /* Bag */0
                                }), React.createElement("h6", {
                                  className: "icon-title"
                                }, "2 weeks vacation per year")), React.createElement("div", {
                              className: "col-6 col-md pb-3 team-benefits"
                            }, React.createElement(Icon.make, {
                                  iconType: /* Game */6
                                }), React.createElement("h6", {
                                  className: "icon-title"
                                }, "PC, consoles, and VR games at office"))))), React.createElement("div", {
                  className: "footer-title bg-gradient-color2"
                }, React.createElement("p", undefined, "If you are interested in joining our team, just send your portfolio to", React.createElement("a", {
                          className: "text-contact",
                          href: "mailto:contact@divertise.asia",
                          target: "_blank"
                        }, "careers@divertise.asia"))));
}

var make = PageCareers;

export {
  make ,
  
}
/* Icon Not a pure module */
