// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as InputText from "./InputText.mjs";
import * as Js_option from "rescript/lib/es6/js_option.js";

function ContactForm(Props) {
  var className = Props.className;
  var prefixIdOpt = Props.prefixId;
  var prefixId = prefixIdOpt !== undefined ? prefixIdOpt : "";
  return React.createElement("div", {
              className: "contactform-container"
            }, React.createElement("form", {
                  className: "contactform " + Js_option.getWithDefault("contactform-default", className),
                  action: "https://formspree.io/f/xdopdkdk",
                  method: "POST"
                }, React.createElement(InputText.make, {
                      type_: "text",
                      placeholder: "What should we call you?",
                      inputLabel: "Your Name",
                      name: "name",
                      required: true,
                      prefixId: prefixId
                    }), React.createElement(InputText.make, {
                      type_: "email",
                      placeholder: "Your Email",
                      inputLabel: "Your Email",
                      name: "email",
                      required: true,
                      prefixId: prefixId
                    }), React.createElement(InputText.make, {
                      placeholder: "I really want ..",
                      inputLabel: "What do you want to build?",
                      isTextarea: true,
                      name: "content",
                      required: true,
                      prefixId: prefixId
                    }), React.createElement("button", {
                      className: "btn btn-solid-color1",
                      type: "submit"
                    }, "Submit")));
}

var make = ContactForm;

export {
  make ,
  
}
/* react Not a pure module */
