// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "./Icon.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.mjs";
import * as React from "react";
import * as Js_option from "rescript/lib/es6/js_option.js";

function EmailPopover(Props) {
  var className = Props.className;
  var match = React.useState(function () {
        return false;
      });
  var setPopoverOpen = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setCopySuccess = match$1[1];
  var isCopySuccess = match$1[0];
  return React.createElement("div", {
              className: "email email-contact " + Js_option.getWithDefault("", className),
              onMouseOut: (function (param) {
                  Curry._1(setCopySuccess, (function (param) {
                          return false;
                        }));
                  return Curry._1(setPopoverOpen, (function (param) {
                                return false;
                              }));
                }),
              onMouseOver: (function (param) {
                  return Curry._1(setPopoverOpen, (function (param) {
                                return true;
                              }));
                })
            }, React.createElement(Icon.make, {
                  iconType: /* EmailContact */11
                }), React.createElement("div", {
                  className: "email_popover popover-default " + (
                    match[0] ? "popover-open" : "popover-close"
                  )
                }, React.createElement("a", {
                      href: "mailto:contact@divertise.asia",
                      target: "_blank"
                    }, "Open mail app"), React.createElement("div", {
                      onClick: (function (param) {
                          Utils.copyToClipboard("contact@divertise.asia").then(function (param) {
                                  return Promise.resolve(Curry._1(setCopySuccess, (function (param) {
                                                    return true;
                                                  })));
                                }).catch(function (param) {
                                return Promise.resolve(undefined);
                              });
                          
                        })
                    }, React.createElement("div", {
                          className: "copybtn_content copybtn_content-" + (
                            isCopySuccess ? "hide" : "show"
                          )
                        }, "Copy"), React.createElement("div", {
                          className: "copybtn_content copybtn_content-" + (
                            isCopySuccess ? "show" : "hide"
                          )
                        }, React.createElement(Icon.make, {
                              iconType: /* Check */12
                            })))));
}

var make = EmailPopover;

export {
  make ,
  
}
/* Icon Not a pure module */
