// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_option from "rescript/lib/es6/js_option.js";
import Link from "next/link";
import * as ImageBackground from "./ImageBackground.mjs";

function FrontPageSection(Props) {
  var className = Props.className;
  var title = Props.title;
  var imageURL = Props.imageURL;
  var href = Props.href;
  var prefixAlt = Props.prefixAlt;
  var children = Props.children;
  var altText = Js_option.getWithDefault("", prefixAlt) + " see all projects";
  return React.createElement("div", {
              className: "frontpage-section " + Js_option.getWithDefault("frontpage-section-default", className)
            }, React.createElement("div", undefined, React.createElement("div", {
                      className: "row pb-5"
                    }, React.createElement("div", {
                          className: "col-sm-6"
                        }, React.createElement(ImageBackground.make, {
                              src: imageURL
                            })), React.createElement("div", {
                          className: "col-sm-6 frontpage-section-texts pt-5"
                        }, React.createElement("h4", undefined, title), React.createElement("div", {
                              className: "content"
                            }, children), React.createElement(Link, {
                              href: href,
                              children: React.createElement("a", {
                                    className: "btn",
                                    alt: altText
                                  }, "See All Projects")
                            })))));
}

var make = FrontPageSection;

export {
  make ,
  
}
/* react Not a pure module */
