// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_option from "rescript/lib/es6/js_option.js";

function ImageBackground(Props) {
  var className = Props.className;
  var src = Props.src;
  return React.createElement("div", {
              className: "image-background " + Js_option.getWithDefault("image-background-default", className),
              style: {
                backgroundImage: "url(\"" + src + "\")"
              }
            });
}

var make = ImageBackground;

export {
  make ,
  
}
/* react Not a pure module */
