// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_option from "rescript/lib/es6/js_option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LoadingGif from "../../../../public/images/loading.gif";

var loading = LoadingGif;

function Loading(Props) {
  var className = Props.className;
  var onClick = Props.onClick;
  var tmp = {
    className: "loading " + Js_option.getWithDefault("loading-default", className),
    src: loading
  };
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement("img", tmp);
}

var make = Loading;

export {
  loading ,
  make ,
  
}
/* loading Not a pure module */
