// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Links from "../Links.mjs";
import * as React from "react";
import * as Js_option from "rescript/lib/es6/js_option.js";
import Link from "next/link";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function Logo(Props) {
  var className = Props.className;
  var onClick = Props.onClick;
  var is404 = Props.is404;
  var tmp = {
    className: "logo " + Js_option.getWithDefault("logo-default", className),
    src: "/static/images/logo.png"
  };
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement(Link, {
              href: Links.home,
              children: React.createElement("a", {
                    className: "link logo-link " + (
                      Js_option.getWithDefault(false, is404) ? "btn btn-404 btn-line-color1" : ""
                    )
                  }, React.createElement("img", tmp), Js_option.getWithDefault(false, is404) ? React.createElement("h2", {
                          className: "go-home"
                        }, "Go Home") : null)
            });
}

var make = Logo;

export {
  make ,
  
}
/* react Not a pure module */
