// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_option from "rescript/lib/es6/js_option.js";

function PageHeader(Props) {
  var className = Props.className;
  var title = Props.title;
  var subtitle = Props.subtitle;
  var tmp;
  tmp = subtitle !== undefined && subtitle !== "" ? React.createElement("h2", {
          className: "text-white letter-spacing -text-header-shadow"
        }, "-  " + subtitle) : null;
  return React.createElement("div", {
              className: "section-header " + Js_option.getWithDefault("", className)
            }, React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row d-flex align-items-baseline -text-uppercase"
                    }, React.createElement("h1", {
                          className: "text-white letter-spacing -text-header-shadow"
                        }, title), tmp)));
}

var make = PageHeader;

export {
  make ,
  
}
/* react Not a pure module */
