// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DataTypes from "../Data/DataTypes.mjs";
import * as Js_option from "rescript/lib/es6/js_option.js";

function PortfolioImage(Props) {
  var className = Props.className;
  var item = Props.item;
  return React.createElement("div", {
              className: " " + Js_option.getWithDefault("", className) + " " + Js_option.getWithDefault("", item.className) + " " + DataTypes.PortfolioItem.getImageBorderClass(item.border)
            }, React.createElement("div", {
                  className: "portimg-container"
                }, React.createElement("div", {
                      className: "portimg"
                    }, React.createElement("div", {
                          className: "portimg_frame"
                        }, React.createElement("div", {
                              className: "portimg_scroll-before"
                            }), React.createElement("div", {
                              className: "image-background portimg_scroll scroll-long " + item.src
                            }, React.createElement("div", undefined))), React.createElement("div", {
                          className: "portimg_frame-after"
                        }))));
}

var make = PortfolioImage;

export {
  make ,
  
}
/* react Not a pure module */
