// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "rescript/lib/es6/list.js";
import * as React from "react";
import * as TechIcon from "./TechIcon.mjs";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Js_option from "rescript/lib/es6/js_option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as PortfolioImage from "./PortfolioImage.mjs";

function additional_classname(category) {
  var tmp;
  switch (category) {
    case /* All */0 :
        tmp = "all";
        break;
    case /* AI */1 :
        tmp = "ai";
        break;
    case /* Other */2 :
        tmp = "other";
        break;
    case /* Design */3 :
        tmp = "design";
        break;
    case /* AppPlatforms */4 :
        tmp = "appsandplatforms";
        break;
    
  }
  return "item-" + tmp;
}

function PortfolioItem(Props) {
  var id = Props.id;
  var classNameOpt = Props.className;
  var item = Props.item;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var tmp = {
    className: "section-portfolio " + className + " " + Js_option.getWithDefault("section-portfolio-default", item.className) + " " + List.fold_left((function (acc, s) {
            return acc + " " + s;
          }), "", List.map(additional_classname, item.category))
  };
  if (id !== undefined) {
    tmp.id = Caml_option.valFromOption(id);
  }
  return React.createElement("div", tmp, React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "port_img-container row"
                    }, Belt_List.toArray(Belt_List.map(item.images, (function (img) {
                                return React.createElement(PortfolioImage.make, {
                                            item: img,
                                            key: img.src
                                          });
                              })))), React.createElement("h2", undefined, item.title), React.createElement("div", {
                      className: "row py-4"
                    }, React.createElement("div", {
                          className: "col-md-6 port_icon-container"
                        }, Belt_List.toArray(Belt_List.map(item.technologies, (function (tech) {
                                    return React.createElement(TechIcon.make, {
                                                tech: tech,
                                                key: tech
                                              });
                                  })))), React.createElement("div", {
                          className: "col-md-6 -text-right port_btn-container"
                        }, Belt_List.toArray(Belt_List.map(item.links, (function (link) {
                                    var match = link.category;
                                    var classNames;
                                    switch (match) {
                                      case /* Default */0 :
                                          classNames = "btn-line-color1";
                                          break;
                                      case /* DefaultInactive */1 :
                                          classNames = "btn-line-color1 inactive";
                                          break;
                                      case /* Text */2 :
                                          classNames = "port_link_text";
                                          break;
                                      case /* AppStore */3 :
                                          classNames = "btn-app-store";
                                          break;
                                      case /* GooglePlay */4 :
                                          classNames = "btn-google-play";
                                          break;
                                      case /* MiStore */5 :
                                          classNames = "btn-mi-store";
                                          break;
                                      
                                    }
                                    return React.createElement("a", {
                                                key: link.href,
                                                className: "port_btn btn " + classNames,
                                                href: link.href,
                                                target: "_blank"
                                              }, link.caption);
                                  }))))), React.createElement("div", {
                      className: "port_texts"
                    }, item.body)));
}

var make = PortfolioItem;

export {
  additional_classname ,
  make ,
  
}
/* react Not a pure module */
