// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_option from "rescript/lib/es6/js_option.js";
import * as ImageBackground from "./ImageBackground.mjs";

function mapStringToTechIconType(icon) {
  var x = icon.toLowerCase();
  switch (x) {
    case "android" :
        return /* Android */2;
    case "circleci" :
        return /* Circleci */3;
    case "cocos" :
        return /* Cocos */4;
    case "css" :
        return /* CSS */5;
    case "django" :
        return /* Django */6;
    case "docker" :
        return /* Docker */7;
    case "firebase" :
        return /* Firebase */8;
    case "git" :
        return /* Git */9;
    case "html5" :
        return /* HTML5 */0;
    case "ios" :
        return /* Ios */10;
    case "js" :
        return /* Js */11;
    case "nodejs" :
        return /* Nodejs */12;
    case "pandas" :
        return /* Pandas */14;
    case "postgresql" :
        return /* Postgresql */13;
    case "python" :
        return /* Python */1;
    case "react" :
        return /* React */16;
    case "reason" :
        return /* Reason */15;
    case "ruby" :
        return /* Ruby */17;
    case "scikitlearn" :
        return /* Scikitlearn */18;
    case "tensorflow" :
        return /* Tensorflow */19;
    case "unity" :
        return /* Unity */20;
    case "ui" :
    case "ux" :
        return /* Other */{
                _0: icon,
                _1: "color2-text-big"
              };
    case "ai" :
    case "aws" :
    case "c++" :
    case "html" :
    case "vr" :
        return /* Other */{
                _0: icon,
                _1: "text-big"
              };
    case "2d animation" :
    case "2d art" :
    case "brand Identity" :
    case "game design" :
    case "graphic design" :
    case "story board" :
    case "video editing" :
    case "web design" :
        return /* Other */{
                _0: icon,
                _1: "color2"
              };
    case "wordpress" :
        return /* Wordpress */21;
    default:
      return /* Other */{
              _0: x,
              _1: x
            };
  }
}

function mapIcon(icon) {
  if (typeof icon !== "number") {
    return {
            techIconType: icon,
            className: icon._1,
            content: React.createElement("h6", undefined, icon._0)
          };
  }
  switch (icon) {
    case /* HTML5 */0 :
        return {
                techIconType: icon,
                className: "html5",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/html5-logo.png"
                    })
              };
    case /* Python */1 :
        return {
                techIconType: icon,
                className: "python",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_python.png"
                    })
              };
    case /* Android */2 :
        return {
                techIconType: icon,
                className: "android",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_android.png"
                    })
              };
    case /* Circleci */3 :
        return {
                techIconType: icon,
                className: "circleci",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_circleci.png"
                    })
              };
    case /* Cocos */4 :
        return {
                techIconType: icon,
                className: "cocos",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_cocos.png"
                    })
              };
    case /* CSS */5 :
        return {
                techIconType: icon,
                className: "css",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_css.png"
                    })
              };
    case /* Django */6 :
        return {
                techIconType: icon,
                className: "django",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_django.png"
                    })
              };
    case /* Docker */7 :
        return {
                techIconType: icon,
                className: "docker",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_docker.png"
                    })
              };
    case /* Firebase */8 :
        return {
                techIconType: icon,
                className: "firebase",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_firebase.png"
                    })
              };
    case /* Git */9 :
        return {
                techIconType: icon,
                className: "git",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_git.png"
                    })
              };
    case /* Ios */10 :
        return {
                techIconType: icon,
                className: "ios",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_ios.png"
                    })
              };
    case /* Js */11 :
        return {
                techIconType: icon,
                className: "js",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_js.png"
                    })
              };
    case /* Nodejs */12 :
        return {
                techIconType: icon,
                className: "nodejs",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_nodejs.png"
                    })
              };
    case /* Postgresql */13 :
        return {
                techIconType: icon,
                className: "postgresql",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_postgresql.png"
                    })
              };
    case /* Pandas */14 :
        return {
                techIconType: icon,
                className: "pandas",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_pandas.png"
                    })
              };
    case /* Reason */15 :
        return {
                techIconType: icon,
                className: "reason",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_reason.png"
                    })
              };
    case /* React */16 :
        return {
                techIconType: icon,
                className: "react",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_react.png"
                    })
              };
    case /* Ruby */17 :
        return {
                techIconType: icon,
                className: "ruby",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_ruby.png"
                    })
              };
    case /* Scikitlearn */18 :
        return {
                techIconType: icon,
                className: "scikitlearn",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_scikitlearn.png"
                    })
              };
    case /* Tensorflow */19 :
        return {
                techIconType: icon,
                className: "tensorflow",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_tensorflow.png"
                    })
              };
    case /* Unity */20 :
        return {
                techIconType: icon,
                className: "unity",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_unity.png"
                    })
              };
    case /* Wordpress */21 :
        return {
                techIconType: icon,
                className: "wordpress",
                content: React.createElement(ImageBackground.make, {
                      src: "/static/images/tech-icon/tech-icon_wordpress.png"
                    })
              };
    
  }
}

function TechIcon(Props) {
  var tech = Props.tech;
  var className = Props.className;
  var techIconType = mapStringToTechIconType(tech);
  var icon = mapIcon(techIconType);
  return React.createElement("div", {
              className: "tech-icon tech-icon-" + icon.className + " " + Js_option.getWithDefault("", className)
            }, icon.content);
}

var make = TechIcon;

export {
  mapStringToTechIconType ,
  mapIcon ,
  make ,
  
}
/* react Not a pure module */
