// Generated by ReScript, PLEASE EDIT WITH CARE


var ourwork = "/ourwork";

function ourwork_link(category) {
  var tmp;
  switch (category) {
    case /* All */0 :
        tmp = "all";
        break;
    case /* AI */1 :
        tmp = "ai";
        break;
    case /* Other */2 :
        tmp = "other";
        break;
    case /* Design */3 :
        tmp = "design";
        break;
    case /* AppPlatforms */4 :
        tmp = "appsandplatforms";
        break;
    
  }
  return "/ourwork#" + tmp;
}

function ourwork_link_category(link) {
  switch (link) {
    case "ai" :
        return /* AI */1;
    case "all" :
        return /* All */0;
    case "appsandplatforms" :
        return /* AppPlatforms */4;
    case "design" :
        return /* Design */3;
    case "other" :
        return /* Other */2;
    default:
      return /* All */0;
  }
}

var home = "/";

var careers = "/careers";

var contact = "/contact";

var careersdesigner = "/careers/designer";

var careersdeveloper = "/careers/developer";

var internshipdesign = "/internships/design";

var internshipdeveloper = "/internships/developer";

export {
  home ,
  careers ,
  contact ,
  careersdesigner ,
  careersdeveloper ,
  internshipdesign ,
  internshipdeveloper ,
  ourwork ,
  ourwork_link ,
  ourwork_link_category ,
  
}
/* No side effect */
