// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Navigator = {};

function copyToClipboard(s) {
  return navigator.clipboard.writeText(s);
}

export {
  $$Navigator ,
  copyToClipboard ,
  
}
/* No side effect */
